### ISSUE TITLE
Investigate broken badge for the Reverse Asciidoctor

### ISSUE THREAD

**Issue by skalee** [metanorma/dashboard#10]
See this picture:

> ![Zrzut ekranu 2020-02-20 o 03 02 06](https://user-images.githubusercontent.com/154287/74893809-84b26780-538d-11ea-84c4-27dfca04eda1.png)

It was broken prior merging #8 in. Also visiting https://codeclimate.com/github/metanorma/reverse_adoc results with HTTP Error 404. Either the URL is incorrect, or CodeClimate is not enabled for this repository. Badge on project's page (https://github.com/metanorma/reverse_adoc) is also broken.

Possible resolutions:

– fix badge
– delete badge

**Comment by CAMOBAP** [comment]
@ronaldtse I have no access to codeclimate dashboard, could you please add those repos to codeclimate, or let me know if badges can be removed

**Comment by ronaldtse** [comment]
@skalee @CAMOBAP this link works now:
https://codeclimate.com/github/metanorma/reverse_adoc

**Comment by skalee** [comment]
Works for me too. Thanks!
