### ISSUE TITLE
Investigate broken badges for Metanorma-Docker

### ISSUE THREAD

**Issue by skalee** [metanorma/dashboard#11]
See this picture:

>  ![Zrzut ekranu 2020-02-20 o 03 11 58](https://user-images.githubusercontent.com/154287/74894303-d3accc80-538e-11ea-9d07-6bbe4625fae0.png)

– AppVeyor badge does not work, clicking it gives HTTP 404
– Travis badge is likely outdated and unnecessary
– Releases badge is invalid (the project uses Git tags, not full-blown GitHub releases this badge is supposed to show)

Possible resolutions: fix, remove, or replace badges.

It was broken prior merging #8 in.

**Comment by CAMOBAP** [comment]
Fixed
