### ISSUE TITLE
Investigate broken badges for Metanorma templates

### ISSUE THREAD

**Issue by skalee** [metanorma/dashboard#9]
See this picture:

>  ![Zrzut ekranu 2020-02-20 o 02 57 48](https://user-images.githubusercontent.com/154287/74893501-d73f5400-538c-11ea-98a1-c5c358bd8be7.png)

The reason is that many templates do not follow the convention, for example `mn-templates-ietf` has following workflows defined:

>  ![Zrzut ekranu 2020-02-20 o 02 58 52](https://user-images.githubusercontent.com/154287/74893600-0b1a7980-538d-11ea-870f-669a91ec8a87.png)

It was broken prior merging #8 in.

**Comment by CAMOBAP** [comment]
Done
